// <auto-generated />
using System;
using GalaxyFootball.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Database.Layer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260429213810_creation-year-day")]
    partial class creationyearday
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.AutoCoach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LineupFormationSelectionMethod")
                        .HasColumnType("integer");

                    b.Property<int>("LineupPickStrategySelectionMethod")
                        .HasColumnType("integer");

                    b.Property<int>("PreferredLineUpFormation")
                        .HasColumnType("integer");

                    b.Property<int>("PreferredLineupPickStrategy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AutoCoaches");
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.AutoCoachClubTeam", b =>
                {
                    b.Property<Guid>("AutoCoachId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("AutoCoachId", "ClubId", "TeamId");

                    b.ToTable("autocoach_club_teams", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AllTimeGamesDrawn")
                        .HasColumnType("integer");

                    b.Property<int>("AllTimeGamesLost")
                        .HasColumnType("integer");

                    b.Property<int>("AllTimeGamesWon")
                        .HasColumnType("integer");

                    b.Property<int>("AllTimeGoalsConceded")
                        .HasColumnType("integer");

                    b.Property<int>("AllTimeGoalsScored")
                        .HasColumnType("integer");

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<int>("ClubRankingPoints")
                        .HasColumnType("integer");

                    b.Property<int>("FanCount")
                        .HasColumnType("integer");

                    b.Property<int>("FanExpectations")
                        .HasColumnType("integer");

                    b.Property<int>("FanHappiness")
                        .HasColumnType("integer");

                    b.Property<int>("FoundationYear")
                        .HasColumnType("integer");

                    b.Property<int>("LastExpenses")
                        .HasColumnType("integer");

                    b.Property<int>("LastIncome")
                        .HasColumnType("integer");

                    b.Property<string>("LogoReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LosingStreak")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeasonGamesDrawn")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonGamesLost")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonGamesWon")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonGoalsConceded")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonGoalsScored")
                        .HasColumnType("integer");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TertiaryColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniformStyle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WinningStreak")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("clubs", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.ClubCupResult", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CupResultId")
                        .HasColumnType("uuid");

                    b.HasKey("ClubId", "CupResultId");

                    b.ToTable("club_cup_results", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.ClubLeagueResult", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeagueResultId")
                        .HasColumnType("uuid");

                    b.HasKey("ClubId", "LeagueResultId");

                    b.ToTable("club_league_results", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.ClubSponsor", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SponsorId")
                        .HasColumnType("uuid");

                    b.HasKey("ClubId", "SponsorId");

                    b.ToTable("club_sponsors", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.ClubStadium", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StadiumId")
                        .HasColumnType("uuid");

                    b.HasKey("ClubId", "StadiumId");

                    b.ToTable("club_stadiums", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.ClubTeam", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("ClubId", "TeamId");

                    b.ToTable("club_teams", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentCupRound")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentLeagueRound")
                        .HasColumnType("integer");

                    b.Property<int>("DatabaseVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<int>("DaysBetweenGames")
                        .HasColumnType("integer");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProcessing")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxCupRounds")
                        .HasColumnType("integer");

                    b.Property<int>("MaxLeagueRounds")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfTeamsInLeague")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("leagues", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.LeagueLeagueResult", b =>
                {
                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeagueResultId")
                        .HasColumnType("uuid");

                    b.HasKey("LeagueId", "LeagueResultId");

                    b.ToTable("league_league_results", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.LeagueResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AwayDraws")
                        .HasColumnType("integer");

                    b.Property<int>("AwayGoalsAgainst")
                        .HasColumnType("integer");

                    b.Property<int>("AwayGoalsFor")
                        .HasColumnType("integer");

                    b.Property<int>("AwayLosses")
                        .HasColumnType("integer");

                    b.Property<int>("AwayPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("AwayWins")
                        .HasColumnType("integer");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("HomeDraws")
                        .HasColumnType("integer");

                    b.Property<int>("HomeGoalsAgainst")
                        .HasColumnType("integer");

                    b.Property<int>("HomeGoalsFor")
                        .HasColumnType("integer");

                    b.Property<int>("HomeLosses")
                        .HasColumnType("integer");

                    b.Property<int>("HomePlayed")
                        .HasColumnType("integer");

                    b.Property<int>("HomeWins")
                        .HasColumnType("integer");

                    b.Property<int>("LosingStreak")
                        .HasColumnType("integer");

                    b.Property<string>("MatchResults")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("WinningStreak")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("league_results", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.PlayerClubTeam", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("PlayerId", "ClubId", "TeamId");

                    b.ToTable("player_club_teams", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.Robot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatteryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BodyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrainId")
                        .HasColumnType("uuid");

                    b.Property<int>("CreationDay")
                        .HasColumnType("integer");

                    b.Property<int>("CreationYear")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentCondition")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentMentalShape")
                        .HasColumnType("integer");

                    b.Property<string>("Face")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Fatigue")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MatchesBannedRemaining")
                        .HasColumnType("integer");

                    b.Property<int>("MatchesUnavailableRemaining")
                        .HasColumnType("integer");

                    b.Property<Guid>("MotorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Planet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecoveryRate")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("WearSpeed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("robots", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.RobotBattery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("ConversionEfficiency")
                        .HasColumnType("integer");

                    b.Property<int>("DischargeRate")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("robot_batteries", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.RobotBody", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Mass")
                        .HasColumnType("integer");

                    b.Property<int>("RotationResistance")
                        .HasColumnType("integer");

                    b.Property<int>("ShootingPower")
                        .HasColumnType("integer");

                    b.Property<int>("Traction")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("robot_bodies", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.RobotBrain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Anticipation")
                        .HasColumnType("integer");

                    b.Property<int>("BrainType")
                        .HasColumnType("integer");

                    b.Property<int>("ReactionTime")
                        .HasColumnType("integer");

                    b.Property<int>("ShootingAccuracy")
                        .HasColumnType("integer");

                    b.Property<int>("ViewRange")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("robot_brains", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.RobotMotor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Acceleration")
                        .HasColumnType("integer");

                    b.Property<int>("Braking")
                        .HasColumnType("integer");

                    b.Property<int>("CoolingRate")
                        .HasColumnType("integer");

                    b.Property<int>("HeatGenerationRate")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRotationSpeed")
                        .HasColumnType("integer");

                    b.Property<int>("MaxSpeed")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTemperature")
                        .HasColumnType("integer");

                    b.Property<int>("RotationAcceleration")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("robot_motors", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.SeasonCupResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Ranking")
                        .HasColumnType("integer");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("season_cup_results", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.SeasonLeagueResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DivisionLevel")
                        .HasColumnType("integer");

                    b.Property<int>("DivisionNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Ranking")
                        .HasColumnType("integer");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("season_league_results", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.Stadium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Facilities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaintenanceCost")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PitchType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Planet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TicketPrice")
                        .HasColumnType("integer");

                    b.Property<string>("WeatherTendencies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stadiums");
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.TeamCompetition", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.HasKey("TeamId", "CompetitionId");

                    b.ToTable("team_competitions", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.TeamMatchLineup", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MatchLineupId")
                        .HasColumnType("uuid");

                    b.HasKey("TeamId", "MatchLineupId");

                    b.ToTable("team_match_lineups", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.TeamRobot", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RobotId")
                        .HasColumnType("uuid");

                    b.HasKey("TeamId", "RobotId");

                    b.ToTable("team_robots", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.TeamSavedLineup", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SavedLineupId")
                        .HasColumnType("uuid");

                    b.HasKey("TeamId", "SavedLineupId");

                    b.ToTable("team_saved_lineups", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.UserPlayer", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "PlayerId");

                    b.ToTable("user_players", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
