// <auto-generated />
using System;
using GalaxyFootball.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Database.Layer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260427161047_ClubTeamLeagueRobot")]
    partial class ClubTeamLeagueRobot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AllTimeGamesDrawn")
                        .HasColumnType("integer");

                    b.Property<int>("AllTimeGamesLost")
                        .HasColumnType("integer");

                    b.Property<int>("AllTimeGamesWon")
                        .HasColumnType("integer");

                    b.Property<int>("AllTimeGoalsConceded")
                        .HasColumnType("integer");

                    b.Property<int>("AllTimeGoalsScored")
                        .HasColumnType("integer");

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<int>("ClubRankingPoints")
                        .HasColumnType("integer");

                    b.Property<int>("FanCount")
                        .HasColumnType("integer");

                    b.Property<int>("FanExpectations")
                        .HasColumnType("integer");

                    b.Property<int>("FanHappiness")
                        .HasColumnType("integer");

                    b.Property<int>("FoundationYear")
                        .HasColumnType("integer");

                    b.Property<int>("LastExpenses")
                        .HasColumnType("integer");

                    b.Property<int>("LastIncome")
                        .HasColumnType("integer");

                    b.Property<string>("LogoReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LosingStreak")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeasonGamesDrawn")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonGamesLost")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonGamesWon")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonGoalsConceded")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonGoalsScored")
                        .HasColumnType("integer");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TertiaryColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniformStyle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WinningStreak")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("clubs", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentCupRound")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentLeagueRound")
                        .HasColumnType("integer");

                    b.Property<int>("DatabaseVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<int>("DaysBetweenGames")
                        .HasColumnType("integer");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProcessing")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxCupRounds")
                        .HasColumnType("integer");

                    b.Property<int>("MaxLeagueRounds")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfTeamsInLeague")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("GalaxyFootball.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
